before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: c7OP9iZ4wdxV+0Qn/hx65MECLPeH9KQo83pXbFCkdLRitj1H5GvXn5PUxcWumtVLF3WrkgysLys4hklavN8oJP4sGVMR1FduzQZ5hSTZtGmg+5uPl3KmTR/kZc2VJJtL5oWU5nVZ4OqqJ1NC2nRiX3RGQgeygIwRKfAX1kCVY2Gkyc+9SEvH9QDoTZWSO41CHpsaRG2ljGYG2Y0p+W94oKpTD0gU+EDn5lzCH2L842GM+bRUz3aEOdCkwAIFCdfKvohtSrgrMj2VmyV1EHYUPtxeeI3uLo893D3OnNPcfWplxU/ooQm7IXbdI+XoVU1IFqYoE0MOMEYuKVm3gL8apkws5AEhUCGi8n2QkJGg5k6mJVqyVbn9Wu5fP/Pee3FM3jqzhv7wWSk9vSuNRulSIpz+0VojmL3mrBAaexKqYoJHq3/W5rYt1nQbkOIdMU1Qj+z44MII8Qkc/5m22ZNojxzY0Jn/QgX91Pu645y1e7Rq509T0veVgt30M7/yHUPr55Ozt9cNUDji0amDt8onHzmEvU8RNgafmnhMHoXqvzd2zU0K+OwgrIdoTk8RFvCkiroRJDMdBiBWHizmPiydhW76hksclD+FepmveXgURS1aS/RTGsvhWMQD1LPCaDw7EFByk/xkXUSNBIaggjLkihJK9KIZ5XTPgsiHk01h4aE= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
